name: Vision Unbound
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50133
title: Vision Unbound
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9aa5ab'
    - '#fffffd'
    - '#5c6165'
    - '#000500'
    - '#23361a'
  brandStrength: 0.5824057541321963
  lightness: 0.7132308327127248
  saturation: 0.630747735965997
  rhythmicContrast: 0.3898173894267529
purpose: []
