name: Vision Unbound
favicon: null
layout_spectrum: 0.922373099019751
typography_spectrum: 0.3162835428956896
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5824057541321963
  lightness: 0.7132308327127248
  saturation: 0.630747735965997
  rhythmicContrast: 0.3898173894267529
purpose: []
